name: CI
on: push

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js version ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Checking for missing or duplicate IDs
      run: node .github/workflows/checkForDuplicateIds.js
